ALTER TABLE "Workout" ADD COLUMN IF NOT EXISTS "strengthBlocks" JSONB;
ALTER TABLE "Workout" ADD COLUMN IF NOT EXISTS "warmup" TEXT;
ALTER TABLE "Workout" ADD COLUMN IF NOT EXISTS "cooldown" TEXT;
ALTER TABLE "Workout" ADD COLUMN IF NOT EXISTS "coachingCues" TEXT;
